name: dartdocorg
description: Generates the Dart documentation for all the packages in pub
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  args: any
  googleapis_auth: any
  googleapis_beta: any
  googleapis: any
  http: any
  intl: any
  logging: any
  path: any
  pub_semver: any
  yaml: any
dev_dependencies:
  grinder: any
  linter: any
  tuneup: any
