name: dartdocorg
description: Generates the Dart documentation for all the packages in pub
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  args: ^0.13.2
  googleapis_auth: ^0.2.3+1
  googleapis_beta: ^0.20.0
  googleapis: ^0.18.0
  http: ^0.11.3+2
  intl: ^0.12.4+2
  logging: ^0.11.2
  path: ^1.3.6
  pub_semver: ^1.2.3
  stack_trace: ^1.5.0
  yaml: ^2.1.7
dev_dependencies:
  grinder: ^0.8.0
  linter: ^0.1.4
  test: ^0.12.5+1
  tuneup: ^0.1.3+1
